#!/bin/bash
# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

{
read header

header=($header)
len=${#header[@]}
while read software_version_line
do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        IMAGE_TAG="${DOCKER_REPO}:v${software_version_line}-${DOCKER_TAG}"
        versions=($software_version_line)
	args=""
	for (( i=0; i<$len; i++ )); do
		args=$(printf "%s%s %s=%s" "$args" "--build-arg" "${header[$i]}" "${versions[$i]} ")
	done
		
        echo "docker build -f Dockerfile $args -t ${IMAGE_TAG} ../"
        docker docker build . $args -t ${IMAGE_TAG} ../
done
} < yarp_versions.txt
