#!/bin/bash
# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

{
read header

header=($header)
len=${#header[@]}
while read software_version_line
do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        versions=($software_version_line)
        IMAGE_TAG="${DOCKER_REPO}:${versions[0]}_v${versions[1]}"

	args=""
	for (( i=0; i<$len; i++ )); do
		args=$(printf "%s%s %s=%s" "$args" "--build-arg" "${header[$i]}" "${versions[$i]} ")
	done
		
        echo "docker build $args -t ${IMAGE_TAG} ."
        # docker build $args -t ${IMAGE_TAG} .
done
} < yarp_versions.txt
