#!/bin/bash
# original docker push command
echo "overwriting docker push $IMAGE_NAME"

{
read header

while read software_version_line
do
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        versions=($software_version_line)
        IMAGE_TAG="${DOCKER_REPO}:v${versions[0]}"
		
        echo "docker push ${IMAGE_TAG}"
        docker push ${IMAGE_TAG}
done
} < yarp_versions.txt
